In [6]:
# utilizado para la manipulación de directorios y rutas
import os
import numpy as np# Cálculo científico y vectorial para python
from matplotlib import pyplot #graficos
import pandas as pd
from scipy import optimize # Modulo de optimizacion en scipy
%matplotlib inline

cargamos el dataset que vamos a utilizar, en este caso es 'diamonds.csv' que es un datasets con datos sobre diamantes, su peso, corte, color, precio entre otros.

In [7]:
#Importamos el dataset
data = pd.read_csv('./diamonds.csv', delimiter=',')

In [8]:
data #mostramos el dataset

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

ahora agregamos la columna "RANGO DE PRECIO" de texto que estar en base a la columna de precio (price) donde realizaremos una divisi[on por rangos de precios para agregar un texto consistente y no al azar]

In [9]:
# Agregar una columna de texto aleatorio

conditions = [
    (data['price'] <= 500),         # super economico
    (data['price'] > 500) & (data['price'] < 1500),  # economico
    (data['price'] >= 1500) & (data['price'] < 2500),  # precio normal
    (data['price'] >= 2500) & (data['price'] < 3500),  # costoso
    (data['price'] >= 3500)         # muy costoso
]

# Definir los valores correspondientes a cada condición
choices = ['super economico', 'economico', 'precio normal', 'costoso', 'muy costoso']

# Crear la nueva columna 'economico' basada en las condiciones
data['rango de precio'] = np.select(conditions, choices)
data # Mostrar los primeros datos con la nueva columna

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,rango de precio
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,super economico
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,super economico
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,super economico
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,super economico
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,super economico
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,costoso
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,costoso
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,costoso
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,costoso
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,costoso

agregamos la siguiente columna que se llama CALIDAD DEL CORTE que estara en basre a la columna corte (cut) y asignara un caracter de aucerdo al corte que tenga el diamante

In [10]:
# Agregar una columna de caracter

conditions = [
    (data['cut'] == 'Ideal'),         
    (data['cut'] == 'Premium'),  
    (data['cut'] == 'Good'),  
    (data['cut'] == 'Very Good'),  
    (data['cut'] == 'Fair')         
]

# Definir los valores correspondientes a cada condición
choices = ['i', 'p', 'g', 'v', 'f']

# Crear la nueva columna 'calidad_del_corte' basada en las condiciones
data['calidad_del_corte'] = np.select(conditions, choices)
data

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,rango de precio,calidad_del_corte
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,super economico,i
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,super economico,p
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,super economico,g
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,super economico,p
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,super economico,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,costoso,i
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,costoso,g
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,costoso,v
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,costoso,p
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,costoso,i

Agregamos la ultima columna "PESADO" que esTA en base a la coluna de de peso y en base al peso del diamante asigna un valor boolena ('si','no') dependiendo del peso que tenga

In [11]:
#anadir columna de valores booleanos

data['pesado'] = np.where(data['carat'] > 0.5, True, False)
data

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,rango de precio,calidad_del_corte,pesado
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,super economico,i,False
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,super economico,p,False
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,super economico,g,False
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,super economico,p,False
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,super economico,g,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50,costoso,i,True
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61,costoso,g,True
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56,costoso,v,True
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74,costoso,p,True
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64,costoso,i,True

ahora realizamos el duplicado de nuestro dataset, lo que quiere decir que debe suplicar las filas, no las columnas del dataset

In [23]:
# Duplicar el dataset
df_duplicate = data.copy()
print('copia del Dataset')
print(df_duplicate.shape)

# Aplicar variaciones a las primeras 7 columnas
numeric_columns= df_duplicate.iloc[:, 0:14].select_dtypes(include=['float64', 'int64']).columns
#df_duplicate[numeric_columns] += np.random.normal(0, 0.05, size=(len(df_duplicate), len(numeric_columns)))
df_duplicate.iloc[:, 0:14]+=np.random.normal(-0.5, 0.5,size=(len(df_duplicate), len(numeric_columns)))
# Introducir pequeñas variaciones a las columnas numéricas del dataset duplicado
#for column in df_duplicate.columns:
    #if df_duplicate[column].dtype in ['float64', 'int64']:  # Solo para columnas numéricas
      #  variation = np.random.normal(0, 0.05, size=len(df_duplicate))
        #df_duplicate[column] = df_duplicate[column] + variation

# Concatenar el dataset original con el duplicado
df_final = pd.concat([data, df_duplicate], ignore_index=True)

# Mostrar el dataset final
#print(df_final)
df_final

copia del Dataset
(53940, 14)

ValueError: Unable to coerce to DataFrame, shape must be (53940, 8): given (53940, 5)